# fly.toml app configuration file generated for viveonfit-app on 2023-10-17T10:22:31+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "viveonfit-app"
primary_region = "mad"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]
